<?php
/**
 * Created by PhpStorm.
 * User: Joaquin
 * Date: 15/03/2015
 * Time: 09:27 PM
 */
use Faker\Factory as Faker;
use Voiture\Entities\Utilisateur;
use Voiture\Entities\User;
use Voiture\Entities\BankAccount;
use Voiture\Entities\Operation;
use Voiture\Entities\Voiture;
class UsersTableSeeder extends Seeder {

    public function run()
    {
        $faker = Faker::create();
        foreach(range(1, 500) as $index)
        {
            $utilisateur = Utilisateur::create([
                'pseudo'        => $faker->userName,
                'password'      => \Hash::make('123'),
                'role_id'       =>6
            ]);
            $user = User::create([
                'id'            =>$utilisateur->id,
                'prenom'        => $faker->firstName($gender = null|'male'|'female'),
                'nom'           => $faker->lastName ,
                'email'         => $faker->email,
                'role_id'       => $utilisateur->role_id,
                'verified'      => 0,
                'number_attemps' => null,
                'confirmation_code' => null,
                'pseudo'        => $utilisateur->pseudo,
                'date_nac'      => $faker->date($format = 'Y-m-d', $max = '-12 years'),
                'sexe'          => $faker->randomElement(['f','m']),
                'phone'         => $faker->numberBetween($min = 10000000, $max = 1000000000),
                'adr_postale'   => $faker->numberBetween($min = 10000, $max = 99999),
                'avatar'        => $faker->randomElement(['p1.png','p2.png','p3.jpg','p4.jpg','p5.png','p6.png','p7.png','p8.jpg','p9.gif','p10.jpg']),
                'description'   => $faker->text($maxNbChars = 240),
                'website_url'   => $faker->url,
                'adr_ip'        => $faker->ipv4,
                'remember_token' => null,
                'created_at'     => $faker->dateTimeThisYear($max = 'now'),
                'updated_at'    => $faker->dateTimeThisMonth($max = 'now')
            ]);
            BankAccount::create([
                'user_id'        => $user->id,
                'solde'         => $faker->randomNumber($nbDigits = NULL),
                'created_at'    => $faker->dateTimeThisYear($max = 'now'),
                'updated_at'    => $faker->dateTimeThisMonth($max = 'now')
            ]);
        }
        foreach(range(1, 750) as $index)
        {
            Voiture::create([
                'nom_voiture'   => $faker->randomElement(["A4",
                    "A6",
                    "S6",
                    "Coupe",
                    "S2",
                    "Rs2",
                    "A8",
                    "Cabriolet",
                    "S8",
                    "A3",
                    "S4",
                    "Tt",
                    "S3",
                    "Allroad Quattro",
                    "Rs4",
                    "A2",
                    "Rs6",
                    "Q7",
                    "R8",
                    "A5",
                    "S5",
                    "V8",
                    "200",
                    "100",
                    "90",
                    "Tts",
                    "Q5",
                    "A4 Allroad Quattro",
                    "Tt Rs",
                    "Rs5",
                    "A1",
                    "A7",
                    "Rs3",
                    "Q3",
                    "A6 Allroad Quattro",
                    "S7",
                    "Sq5",
                    "Mini",
                    "Montego",
                    "Maestro",
                    "Metro",
                    "Mini Moke",
                    "Diesel",
                    "Brooklands",
                    "Turbo",
                    "Continental",
                    "Azure",
                    "Arnage",
                    "Continental Gt",
                    "Continental Flying Spur",
                    "Turbo R",
                    "Mulsanne",
                    "Eight",
                    "Continental Gtc",
                    "Continental Supersports",
                    "Freeclimber Diesel",
                    "Serie 3",
                    "Serie 5",
                    "Compact",
                    "Serie 7",
                    "Serie 8",
                    "Z3",
                    "Z4",
                    "Z8",
                    "X5",
                    "Serie 6",
                    "X3",
                    "Serie 1",
                    "Z1",
                    "X6",
                    "X1",
                    "Seville",
                    "Sts",
                    "El Dorado",
                    "Cts",
                    "Xlr",
                    "Srx",
                    "Escalade",
                    "Bls",
                    "Corvette",
                    "Blazer",
                    "Astro",
                    "Nubira",
                    "Evanda",
                    "Trans Sport",
                    "Camaro",
                    "Matiz",
                    "Alero",
                    "Tahoe",
                    "Tacuma",
                    "Trailblazer",
                    "Kalos",
                    "Aveo",
                    "Lacetti",
                    "Epica",
                    "Captiva",
                    "Hhr",
                    "Cruze",
                    "Spark",
                    "Orlando",
                    "Volt",
                    "Malibu",
                    "Vision",
                    "300m",
                    "Grand Voyager",
                    "Viper",
                    "Neon",
                    "Voyager",
                    "Stratus",
                    "Sebring",
                    "Sebring 200c",
                    "New Yorker",
                    "Pt Cruiser",
                    "Crossfire",
                    "300c",
                    "Le Baron",
                    "Saratoga",
                    "Xantia",
                    "Xm",
                    "Ax",
                    "Zx",
                    "Evasion",
                    "C8",
                    "Saxo",
                    "C2",
                    "Xsara",
                    "C4",
                    "Xsara Picasso",
                    "C5",
                    "C3",
                    "C3 Pluriel",
                    "C1",
                    "C6",
                    "Grand C4 Picasso",
                    "C4 Picasso",
                    "Ccrosser",
                    "C15",
                    "Jumper",
                    "Jumpy",
                    "Berlingo",
                    "Bx",
                    "C25",
                    "Cx",
                    "Gsa",
                    "Visa",
                    "Lna",
                    "2cv",
                    "Nemo",
                    "C4 Sedan",
                    "Berlingo First",
                    "C3 Picasso",
                    "Ds3",
                    "Czero",
                    "Ds4",
                    "Ds5",
                    "C4 Aircross",
                    "Celysee",
                    "Corvette",
                    "Contac",
                    "Logan",
                    "Sandero",
                    "Duster",
                    "Lodgy",
                    "Nexia",
                    "Aranos",
                    "Lanos",
                    "Nubira",
                    "Compact",
                    "Nubira Compact",
                    "Leganza",
                    "Evanda",
                    "Matiz",
                    "Tacuma",
                    "Kalos",
                    "Lacetti",
                    "Applause",
                    "Charade",
                    "Rocky",
                    "Feroza",
                    "Terios",
                    "Sirion",
                    "Serie Xj",
                    "Xj",
                    "Double Six",
                    "Six",
                    "Series Iii",
                    "Viper",
                    "Caliber",
                    "Nitro",
                    "Avenger",
                    "Journey",
                    "F355",
                    "360",
                    "F430",
                    "F512 M",
                    "550 Maranello",
                    "575m Maranello",
                    "599",
                    "456",
                    "456m",
                    "612",
                    "F50",
                    "Enzo",
                    "Superamerica",
                    "430",
                    "348",
                    "Testarossa",
                    "512",
                    "355",
                    "F40",
                    "412",
                    "Mondial",
                    "328",
                    "California",
                    "458",
                    "Ff",
                    "Croma",
                    "Cinquecento",
                    "Seicento",
                    "Punto",
                    "Grande Punto",
                    "Panda",
                    "Tipo",
                    "Coupe",
                    "Uno",
                    "Ulysse",
                    "Tempra",
                    "Marea",
                    "Barchetta",
                    "Bravo",
                    "Stilo",
                    "Brava",
                    "Palio Weekend",
                    "600",
                    "Multipla",
                    "Idea",
                    "Sedici",
                    "Linea",
                    "500",
                    "Fiorino",
                    "Ducato",
                    "Doblo Cargo",
                    "Doblo",
                    "Strada",
                    "Regata",
                    "Talento",
                    "Argenta",
                    "Ritmo",
                    "Punto Classic",
                    "Qubo",
                    "Punto Evo",
                    "500c",
                    "Freemont",
                    "Panda Classic",
                    "500l",
                    "Maverick",
                    "Escort",
                    "Focus",
                    "Mondeo",
                    "Scorpio",
                    "Fiesta",
                    "Probe",
                    "Explorer",
                    "Galaxy",
                    "Ka",
                    "Puma",
                    "Cougar",
                    "Focus Cmax",
                    "Fusion",
                    "Streetka",
                    "Cmax",
                    "Smax",
                    "Transit",
                    "Courier",
                    "Ranger",
                    "Sierra",
                    "Orion",
                    "Pick Up",
                    "Capri",
                    "Granada",
                    "Kuga",
                    "Grand Cmax",
                    "Bmax",
                    "Tourneo Custom",
                    "Exceed",
                    "Santamo",
                    "Super Exceed",
                    "Accord",
                    "Civic",
                    "Crx",
                    "Prelude",
                    "Nsx",
                    "Legend",
                    "Crv",
                    "Hrv",
                    "Logo",
                    "S2000",
                    "Stream",
                    "Jazz",
                    "Frv",
                    "Concerto",
                    "Insight",
                    "Crz",
                    "H2",
                    "H3",
                    "H3t",
                    "Lantra",
                    "Sonata",
                    "Elantra",
                    "Accent",
                    "Scoupe",
                    "Coupe",
                    "Atos",
                    "H1",
                    "Atos Prime",
                    "Xg",
                    "Trajet",
                    "Santa Fe",
                    "Terracan",
                    "Matrix",
                    "Getz",
                    "Tucson",
                    "I30",
                    "Pony",
                    "Grandeur",
                    "I10",
                    "I800",
                    "Sonata Fl",
                    "Ix55",
                    "I20",
                    "Ix35",
                    "Ix20",
                    "Genesis",
                    "I40",
                    "Veloster",
                    "G",
                    "Ex",
                    "Fx",
                    "M",
                    "Elba",
                    "Minitre",
                    "Trooper",
                    "Pick Up",
                    "D Max",
                    "Rodeo",
                    "Dmax",
                    "Trroper",
                    "Daily",
                    "Massif",
                    "Daily",
                    "Duty",
                    "Serie Xj",
                    "Serie Xk",
                    "Xj",
                    "Stype",
                    "Xf",
                    "Xtype",
                    "Wrangler",
                    "Cherokee",
                    "Grand Cherokee",
                    "Commander",
                    "Compass",
                    "Wrangler Unlimited",
                    "Patriot",
                    "Sportage",
                    "Sephia",
                    "Sephia Ii",
                    "Pride",
                    "Clarus",
                    "Shuma",
                    "Carnival",
                    "Joice",
                    "Magentis",
                    "Carens",
                    "Rio",
                    "Cerato",
                    "Sorento",
                    "Opirus",
                    "Picanto",
                    "Ceed",
                    "Ceed Sporty Wagon",
                    "Proceed",
                    "K2500 Frontier",
                    "K2500",
                    "Soul",
                    "Venga",
                    "Optima",
                    "Ceed Sportswagon",
                    "Samara",
                    "Niva",
                    "Sagona",
                    "Stawra 2110",
                    "214",
                    "Kalina",
                    "Serie 2100",
                    "Priora",
                    "Gallardo",
                    "Murcielago",
                    "Aventador",
                    "Delta",
                    "K",
                    "Y10",
                    "Dedra",
                    "Lybra",
                    "Z",
                    "Y",
                    "Ypsilon",
                    "Thesis",
                    "Phedra",
                    "Musa",
                    "Thema",
                    "Zeta",
                    "Kappa",
                    "Trevi",
                    "Prisma",
                    "A112",
                    "Ypsilon Elefantino",
                    "Voyager",
                    "Range Rover",
                    "Defender",
                    "Discovery",
                    "Freelander",
                    "Range Rover Sport",
                    "Discovery 4",
                    "Range Rover Evoque",
                    "Maxus",
                    "Ls400",
                    "Ls430",
                    "Gs300",
                    "Is200",
                    "Rx300",
                    "Gs430",
                    "Gs460",
                    "Sc430",
                    "Is300",
                    "Is250",
                    "Rx400h",
                    "Is220d",
                    "Rx350",
                    "Gs450h",
                    "Ls460",
                    "Ls600h",
                    "Ls",
                    "Gs",
                    "Is",
                    "Sc",
                    "Rx",
                    "Ct",
                    "Elise",
                    "Exige",
                    "Bolero Pickup",
                    "Goa Pickup",
                    "Goa",
                    "Cj",
                    "Pikup",
                    "Thar",
                    "Ghibli",
                    "Shamal",
                    "Quattroporte",
                    "3200 Gt",
                    "Coupe",
                    "Spyder",
                    "Gransport",
                    "Granturismo",
                    "430",
                    "Biturbo",
                    "228",
                    "224",
                    "Grancabrio",
                    "Maybach",
                    "Xedos 6",
                    "626",
                    "121",
                    "Xedos 9",
                    "323",
                    "Mx3",
                    "Rx7",
                    "Mx5",
                    "Mazda3",
                    "Mpv",
                    "Demio",
                    "Premacy",
                    "Tribute",
                    "Mazda6",
                    "Mazda2",
                    "Rx8",
                    "Mazda5",
                    "Cx7",
                    "Serie B",
                    "B2500",
                    "Bt50",
                    "Mx6",
                    "929",
                    "Cx5",
                    "Clase C",
                    "Clase E",
                    "Clase Sl"]),
                'type'  => $faker->randomElement(['competition','normal']),
                'description'   => $faker->text($maxNbChars = 240),
                'model' => $faker->numberBetween($min = 1981, $max = 2015),
                'fabricant' => $faker->randomElement(["Bmw","Cadillac","Chevrolet","Chrysler","Citroen","Corvette","Dacia","Daewoo","Daf","Daihatsu","Daimler","Dodge","Ferrari","Fiat","Ford","Galloper","Gmc","Honda","Hyundai","Isuzu","Ki","Lada","Land-rover","Lotus","Maybach","Mitsubishi","Opel","Rover","Smart","Vaz","Volkswagen","Volvo","Wartburg","Abarth","Alfa Romeo","Aro","Asia","Asia Motors","Aston Martin","Audi","Austin","Auverland","Bentley","Bertone", "Lamborghini"]),
                'resistance' => $faker->numberBetween($min = 1, $max = 10),
                'rpm' => $faker->numberBetween($min = 2400, $max = 7000),
                'vitesse' => $faker->randomFloat($nbMaxDecimals = 2, $min = 120, $max = 400),
                'cylindres' => $faker->randomElement([6,4,8]),
                'cheval_vapeur' => $faker->numberBetween($min = 300, $max = 1600),
                'taille_recevoir' => $faker->randomFloat($nbMaxDecimals = 2, $min = 30, $max = 400),
                'niveau' => $faker->numberBetween($min = 1, $max = 10),
                'carrosserie' => $faker->randomElement(['Carbon','Carbon fiber','alumnium']),
                'pneus' => $faker->randomElement(['piste','normal','high performance']),
                'châssis' => $faker->randomElement(['Carbon','Carbon fiber','alumnium']),
                'et_stabilite' => $faker->randomElement(['bon état', 'régulier', 'mauvais état']),
                'et_esthetique'=> $faker->randomElement(['bon état', 'régulier', 'mauvais état']),
                'et_performance'=> $faker->randomElement(['bon état', 'régulier', 'mauvais état']),
                'et_equilibre' => $faker->randomElement(['bon état', 'régulier', 'mauvais état']),
                'et_general' => $faker->randomElement(['bon état', 'régulier', 'mauvais état']),
                'created_at'    => $faker->dateTimeThisYear($max = 'now'),
                'updated_at'    => $faker->dateTimeThisMonth($max = 'now')
            ]);

        }

    }
}